In [ ]:
import numpy as np

1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [22]:
array_lst=[12.23, 13.32, 100, 36.32]

arr=np.array(array_lst)
print(f"original list:{array_lst}")
print(f"one dimensional list:{arr}")

original list:[12.23, 13.32, 100, 36.32]
one dimensional list:[ 12.23  13.32 100.    36.32]


2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [20]:
matrix = np.arange(2, 11).reshape(3, 3)

print(matrix)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3.Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [19]:
vector = np.zeros(10)

print("Original vector:")
print(vector)

vector[5] = 11

print("\nUpdated vector:")
print(vector)


Original vector:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Updated vector:
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [ ]:
arr=np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])

print(f"Original array:{arr}")

# reverse arr
reverse=arr[::-1]
print(f"Reverse array:{reverse}")

Original array:[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 1. 1. 1. 1.]]

In [34]:
# matrix 5*5
array = np.ones((5, 5), dtype=float)

array[1:-1, 1:-1] = 0

print("1 on the border and 0 inside in the array:")
print(array)

1 on the border and 0 inside in the array:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 0. 0. 0. 0.]]

In [64]:

original_array = np.ones((3, 3), dtype=float)

print(f"Original array:\n{original_array}")

# Add a border of zeros
bordered_array = np.pad(original_array, pad_width=1)

print(f"border with arrays:\n{bordered_array}")


Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
border with arrays:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [67]:
pattern=np.zeros((8,8),dtype=int)

pattern[1::2,::2]=1
pattern[::2,1::2]=1

print(f"checkboard pattern: \n{pattern}")

checkboard pattern: 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


8. Write a Python program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]

In [70]:
lst=[1,2,3,4,5,6,7,8]
tup=((8,4,6),(1,2,3))

arr_lst=np.array(lst)
arr_tup=np.array(tup)

print(f"list to array:{arr_lst}")
print(f"tuple to array:\n{arr_tup}")

list to array:[1 2 3 4 5 6 7 8]
tuple to array:
[[8 4 6]
 [1 2 3]]


9. Write a Python program to append values to the end of an array.
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [71]:
arr=[10,20,30]
new_arr=np.append(arr,[40,50,60,70,80,90])
print(f"original array:{arr}")
print(f"after appending:{new_arr}")

original array:[10, 20, 30]
after appending:[10 20 30 40 50 60 70 80 90]


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.
Expected Output:
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
Real part of the array:
[ 1. 0.70710678]
Imaginary part of the array:
[ 0. 0.70710678]

In [75]:
arr = np.array([1.0 + 0j, 0.70710678 + 0.70710678j])

print("Original array:", arr)
print("Real part:",arr.real)
print("Imaginary part:", arr.imag)


Original array: [1.        +0.j         0.70710678+0.70710678j]
Real part: [1.         0.70710678]
Imaginary part: [0.         0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.
Expected Output:
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24

In [ ]:
arr = np.array([10, 20, 30])

print("Size of the array:", arr.size)
print("Length of one array element in bytes:", arr.itemsize)
print("Total bytes consumed by the elements:", arr.nbytes)

Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements: 24


12. Write a Python program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]

In [83]:
arr1 = np.array([0, 10, 20, 40, 60])
arr2 = np.array([10, 30, 40])

common_values = np.intersect1d(arr1, arr2)

13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.
Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]

In [84]:
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70, 90])

difference = np.setdiff1d(arr1, arr2)
print("Set difference:", difference)


Set difference: [ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]

In [ ]:
arr1 = np.array([0, 10, 20, 40, 60, 80])
arr2 = np.array([10, 30, 40, 50, 70])

xor_values = np.setxor1d(arr1, arr2)
print("Unique values in only one array:", xor_values)

Unique values in only one array: [ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]

In [86]:
a = np.array([1, 2])
b = np.array([4, 5])

print("a > b:", a > b)
print("a >= b:", a >= b)
print("a < b:", a < b)
print("a <= b:", a <= b)


a > b: [False False]
a >= b: [False False]
a < b: [ True  True]
a <= b: [ True  True]


16. Write a Python program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]

In [ ]:
arr = np.array([[10, 20, 30], [20, 40, 50]])
flattened_arr = arr.flatten()

print("Original array:\n", arr)
print("Flattened array:", flattened_arr)

Original array:
 [[10 20 30]
 [20 40 50]]
Flattened array: [10 20 30 20 40 50]


17. Write a Python program to change the data type of an array.
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Data type of the array x is: int32
New Type: float64
[[ 2. 4. 6.]
[ 6. 8. 10.]]

In [ ]:
arr = np.array([[2, 4, 6], [6, 8, 10]])

print("Original array:\n", arr)
print("Data type of array:", arr.dtype)

# Convert to float
arr_float = arr.astype(np.float64)
print("New array with float values:\n", arr_float)
print("New data type:", arr_float.dtype)


Original array:
 [[ 2  4  6]
 [ 6  8 10]]
Data type of array: int64
New array with float values:
 [[ 2.  4.  6.]
 [ 6.  8. 10.]]
New data type: float64


18. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]

In [ ]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


19. Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]

In [ ]:
arr = np.zeros((4, 3))
arr[1, 0] = 1
arr[2, :2] = 1
arr[3, :] = 1
print(arr)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


20. Write a Python program to concatenate two 2-dimensional arrays.
Expected Output:
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]
Expected Output:
[[ 0 1 3 0 2 4]
[ 5 7 9 6 8 10]]

In [ ]:
arr1 = np.array([[0, 1, 3], [5, 7, 9]])
arr2 = np.array([[0, 2, 4], [6, 8, 10]])

concatenate = np.hstack((arr1, arr2))
print(concatenate)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


21. Write a Python program to make an array immutable (read-only).
Expected Output:
Test the array is read-only or not:
Try to change the value of the first element:
Traceback (most recent call last):
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in
x[0] = 1
ValueError: assignment destination is read-only


22. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.
Expected Output:
Original array elements:
[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]]
New array elements:
[[ 0 3 6 9]
[12 15 18 21]
[24 27 30 33]]


In [103]:
arr=np.arange(12).reshape(3,4)
print(f"original array:\n{arr}")

new_arr=arr*3
print(f"new array:\n{new_arr}")

original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
new array:
[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


23. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[[0 1]
[2 3]
[4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]

In [104]:
arr = np.array([[0, 1], [2, 3], [4, 5]])
print("Original array:\n", arr)

arr_list = arr.tolist()  
print("array converted to list:\n", arr_list)


Original array:
 [[0 1]
 [2 3]
 [4 5]]
array converted to list:
 [[0, 1], [2, 3], [4, 5]]


24. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349
0.35399976 0.99469633 0.0694458 0.54711478]
Print array values with precision 3:
[ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]

In [109]:
np.set_printoptions(precision=3)

arr=np.array([[0.26153123,0.52760141,0.5718299,0.5927067,0.7831874,0.69746349,
0.35399976,0.99469633,0.0694458,0.54711478]])
print(f"array:{arr}")

arr_lst=arr.tolist()
print(f"after converting{arr_lst}")

array:[[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]]
after converting[[0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349, 0.35399976, 0.99469633, 0.0694458, 0.54711478]]


25. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.
Expected Output:
Original array elements:
[ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01]
Print array values with precision 3:
[ 0. 1.6 1200. 0.235]

In [ ]:
arr = np.array([1.6e-10, 1.6, 1.2e3, 2.35e-1])
np.set_printoptions(suppress=True, precision=3) 
print("array without scientific notation:\n", arr)

Array without scientific notation:
 [   0.       1.6   1200.       0.235]



26. Write a Python program to how to add an extra column to an numpy array.
Expected Output:
[[ 10 20 30 100]
[ 40 50 60 200]]

In [113]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
col = np.array([[100], [200]]) 

new_arr = np.hstack((arr, col))  
print("Array after adding extra column:\n", new_arr)


Array after adding extra column:
 [[ 10  20  30 100]
 [ 40  50  60 200]]


27. Write a Python program to remove specific elements in a numpy array.
Expected Output:
Original array:
[ 10 20 30 40 50 60 70 80 90 100]
Delete first, fourth and fifth elements:
[ 20 30 60 70 80 90 100]

In [114]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
remove_ele = [0, 3, 4]  

new_arr = np.delete(arr,remove_ele)  
print("Array after removing specific elements:\n", new_arr)


Array after removing specific elements:
 [ 20  30  60  70  80  90 100]
